### ISSUE TITLE
Can't get Stache to work with Action Mailer

### ISSUE THREAD

**Issue by netflakes** [agoragames/stache#45]
I can't seem to get ActionMailer to play ball with Stache - it works fine with the rest of the application views - am using the "Wrapper" Module for namespacing and this works fine..

Any thoughts? - Thanks

The error I am getting is:
ActionView::Template::Error: wrong constant name ..
	from /Users/steveforkin/.rvm/gems/ruby-2.1.1@chcweb/gems/activesupport-4.1.1/lib/active_support/inflector/methods.rb:240:in `const_get'
	from /Users/steveforkin/.rvm/gems/ruby-2.1.1@chcweb/gems/activesupport-4.1.1/lib/active_support/inflector/methods.rb:240:in `block in constantize'
	from /Users/steveforkin/.rvm/gems/ruby-2.1.1@chcweb/gems/activesupport-4.1.1/lib/active_support/inflector/methods.rb:236:in `each'
	from /Users/steveforkin/.rvm/gems/ruby-2.1.1@chcweb/gems/activesupport-4.1.1/lib/active_support/inflector/methods.rb:236:in `inject'
	from /Users/steveforkin/.rvm/gems/ruby-2.1.1@chcweb/gems/activesupport-4.1.1/lib/active_support/inflector/methods.rb:236:in `constantize'
	from /Users/steveforkin/.rvm/gems/ruby-2.1.1@chcweb/gems/activesupport-4.1.1/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
	from /Users/steveforkin/.rvm/gems/ruby-2.1.1@chcweb/gems/stache-1.0.3/lib/stache/mustache/handler.rb:87:in `mustache_class_from_template'
	from /Users/steveforkin/.rvm/gems/ruby-2.1.1@chcweb/gems/stache-1.0.3/lib/stache/mustache/handler.rb:17:in `compile'
	from /Users/steveforkin/.rvm/gems/ruby-2.1.1@chcweb/gems/stache-1.0.3/lib/stache/mustache/handler.rb:72:in `call'
	from /Users/steveforkin/.rvm/gems/ruby-2.1.1@chcweb/gems/actionview-4.1.1/lib/action_view/template.rb:270:in `compile'
	from /Users/steveforkin/.rvm/gems/ruby-2.1.1@chcweb/gems/actionview-4.1.1/lib/action_view/template.rb:245:in `block (2 levels) in compile!'
	from /Users/steveforkin/.rvm/gems/ruby-2.1.1@chcweb/gems/activesupport-4.1.1/lib/active_support/notifications.rb:161:in `instrument'
	from /Users/steveforkin/.rvm/gems/ruby-2.1.1@chcweb/gems/actionview-4.1.1/lib/action_view/template.rb:339:in `instrument'
	from /Users/steveforkin/.rvm/gems/ruby-2.1.1@chcweb/gems/actionview-4.1.1/lib/action_view/template.rb:244:in `block in compile!'
	from /Users/steveforkin/.rvm/gems/ruby-2.1.1@chcweb/gems/actionview-4.1.1/lib/action_view/template.rb:232:in `synchronize'
	from /Users/steveforkin/.rvm/gems/ruby-2.1.1@chcweb/gems/actionview-4.1.1/lib/action_view/template.rb:232:in `compile!'

# The mustache template sits in app/templates (with the correct folder naming etc..)
<div>
 <p> Welcome...</p>
 {{ full_name }}
 </div>

# I have namespaced view the a wrapper module
module Wrapper
  module Mailers
    module UserMailer
      class ConfirmSignUp < ::Stache::Mustache::View
        def full_name
          [@user.first_name, @user.last_name].join(', ')
        end                                  
      end
    end                                      
  end                                        
end

**Comment by hypomodern** [comment]
I wrote a test case for this and it seems to be working in the latest release. Check the readme section out here: https://github.com/agoragames/stache#stache--actionmailer
