### ISSUE TITLE
Fix not yet released for: undefined method `update' on FasterContext

### ISSUE THREAD

**Issue by mcary** [agoragames/stache#50]
I set up a new rails 4.2.0 project and got this error when rendering my first stache view:

> ActionView::Template::Error: undefined method `update' for #<Stache::Mustache::FasterContext:0x007fd7abc2adf0>

Looks like this is caused by removal of the `update` alias of `push` in mustache/mustache commit mustache a18e49bd.  Then it was fixed in stache by commit a915c955, but that hasn't been released as a rubygem yet.

Maybe it's time for a new release of stache?  I can bundle from github in the mean time, but otherwise I cannot render a view without monkey patching.  It's a rocky first experience with stache.

**Comment by hypomodern** [comment]
1.1.1 will be going out this evening—thanks for your interest!

**Comment by hypomodern** [comment]
it's out

**Comment by mcary** [comment]
Thanks!
